# Generated by Django 5.2.6 on 2025-09-18 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_authorcategory_remove_book_price_author_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(choices=[('general', 'Общий вопрос'), ('cooperation', 'Сотрудничество'), ('manuscript', 'Отправка рукописи'), ('order', 'Заказ книг'), ('other', 'Другое')], max_length=20, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('agree_to_terms', models.BooleanField(verbose_name='Согласие на обработку данных')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ['-created_at'],
            },
        ),
    ]
